version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Test@123 # Testing password for root
      MYSQL_DATABASE: movies_db
      MYSQL_USER: arham
      MYSQL_PASSWORD: Test@12 # Testing password for user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    build: .
    platform: linux/amd64
    container_name: movie-app-container
    ports:
      - "9001:9001"
    environment:
      DATABASE_URL: "mysql://arham:Test@12@mysql-container:3306/movies_db"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    restart: always

volumes:
  mysql_data:
networks:
  app_network:
